#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/start.h"
#include "images/stage.h"
#include "images/win.h"
#include "images/lose.h"
#include "images/character.h"
#include "images/sasuke.h"
#include "images/pain.h"


/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int time = 0;
char timer[10];
int t = 1;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  struct position characterObj;
  characterObj.col = 140;
  characterObj.row = 0;
  const struct position sasukeObj = {40 , 220};
  const struct position painObj = {100, 100};

  //int time = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawImageDMA(0, 0, 240, 160, start);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          vBlankCounter = 0;
          t = 1;
          state = PLAY;
        }
        // state = ?
        break;
      case PLAY:
      if (t == 1){
        fillScreenDMA(DARK_BLUE);
        drawImageDMA(characterObj.col, characterObj.row, CHARACTER_WIDTH, CHARACTER_HEIGHT, character);
        drawImageDMA(sasukeObj.col, sasukeObj.row, SASUKE_WIDTH, SASUKE_HEIGHT, sasuke);
        drawImageDMA(painObj.col, painObj.row, PAIN_WIDTH, PAIN_HEIGHT, pain);
        t = 0;
      }
        //drawImageDMA(0, 0, 240, 160, stage);
        
        snprintf(timer, 10, "%d", time);
        drawString(0, 0, timer, DARK_BLUE);
        time = vBlankCounter / 60;
        snprintf(timer, 10, "%d", time);
        drawString(0, 0, timer, BLACK);

        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          characterObj.row++;
          drawImageDMA(characterObj.col, characterObj.row, CHARACTER_WIDTH,CHARACTER_HEIGHT,character);
          drawRectDMA(characterObj.col, characterObj.row - 1, 1, CHARACTER_HEIGHT, DARK_BLUE);
        }
        if ((KEY_DOWN(BUTTON_LEFT, currentButtons)) && (characterObj.row > 0)){
          characterObj.row--;
          drawImageDMA(characterObj.col, characterObj.row, CHARACTER_WIDTH,CHARACTER_HEIGHT,character);
          drawRectDMA(characterObj.col, characterObj.row + CHARACTER_WIDTH, 1, CHARACTER_HEIGHT, DARK_BLUE);

        }
        if ((KEY_DOWN(BUTTON_UP, currentButtons)) && (characterObj.col > 0)) {
          characterObj.col--;
          drawImageDMA(characterObj.col, characterObj.row, CHARACTER_WIDTH,CHARACTER_HEIGHT,character);

          drawRectDMA(characterObj.col + CHARACTER_HEIGHT, characterObj.row, CHARACTER_WIDTH, 1, DARK_BLUE);

        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (characterObj.col < 160 - CHARACTER_HEIGHT) {
            characterObj.col++;
            drawImageDMA(characterObj.col, characterObj.row, CHARACTER_WIDTH,CHARACTER_HEIGHT,character);
            drawRectDMA(characterObj.col - 1, characterObj.row, CHARACTER_WIDTH, 1, DARK_BLUE);
          }
        }
        if ((characterObj.row + CHARACTER_HEIGHT > painObj.row) && (characterObj.col + CHARACTER_WIDTH > painObj.col) && (characterObj.row < painObj.row + PAIN_HEIGHT) && (characterObj.col < painObj.col + PAIN_WIDTH)) {
          state = LOSE;
        }
        if ((characterObj.row + CHARACTER_WIDTH > sasukeObj.row) && (characterObj.col + CHARACTER_WIDTH > sasukeObj.col) && (characterObj.row < sasukeObj.row + SASUKE_HEIGHT) && (characterObj.col < sasukeObj.col + SASUKE_WIDTH)) {
          state = WIN;
        }


        // state = ?
        break;
      case WIN:
        drawString(0, 0, timer, BLACK);
        drawImageDMA(0, 0, 240, 160, win);
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          characterObj.row = 0;
          characterObj.col = 160 - CHARACTER_HEIGHT;
          vBlankCounter = 0;
          state = START;
        }
        // state = ?
        break;
      case LOSE:
        drawString(0, 0, timer, BLACK);
        drawImageDMA(0, 0, 240, 160, lose);
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          characterObj.row = 0;
          characterObj.col = 160 - CHARACTER_HEIGHT;
          vBlankCounter = 0;
          state = START;
        }
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
  return 0;
}
